# List of custom substitution variables.
# Important - Custom variables must begin with '_'.
substitutions:
  _EXEC_NAME: 'pinger'
  _GO_BUILD_PATH: 'cmd/Pinger/main.go'
  _GITHUB_ORG: 'dillydev'
  _GITHUB_REPO: 'pinger'

# Build steps for the cloud build process.
steps:
# Copy the files from storage needed to connect to git.
- name: 'gcr.io/cloud-builders/gsutil'
  id: copy ssh keys for github
  args: ['cp', 'gs://pipeline-test-20190604/*', '.']

# decrypt ssh keys for git
- name: 'gcr.io/cloud-builders/gcloud'
  id: load github key
  args:
  - kms
  - decrypt
  - --ciphertext-file=id_rsa.enc
  - --plaintext-file=/root/.ssh/id_rsa
  - --location=global
  - --keyring=cloudbuilder
  - --key=github-key
  volumes:
  - name: 'ssh'
    path: /root/.ssh

# Set up git with key and domain.
- name: 'gcr.io/cloud-builders/git'
  id: set ssh key for github
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    chmod 600 /root/.ssh/id_rsa
    cat <<EOF >/root/.ssh/config
    Hostname github.com
    IdentityFile /root/.ssh/id_rsa
    EOF
    mv known_hosts /root/.ssh/known_hosts
  volumes:
  - name: 'ssh'
    path: /root/.ssh

# Build the GO binary.
# Important - The 'golang:alpine' image points to the latest go version.
- name: 'golang:alpine'
  id: Go Build
  args:
  - go
  - build
  - -mod=vendor
  - -o=./$_EXEC_NAME
  - $_GO_BUILD_PATH

# This step builds the container image.
- name: 'gcr.io/cloud-builders/docker'
  id: Build
  args:
  - 'build'
  - --build-arg
  - EXEC_NAME=$_EXEC_NAME
  - '-t'
  - 'gcr.io/$PROJECT_ID/$_EXEC_NAME:$SHORT_SHA'
  - '.'

# Retag the current image into latest.
- name: 'gcr.io/cloud-builders/docker'
  id: Docker Push
  args:
  - 'push'
  - 'gcr.io/$PROJECT_ID/$_EXEC_NAME:$SHORT_SHA'

# clone k8s repo
- name: 'gcr.io/cloud-builders/git'
  id: Checkout k8s repo
  entrypoint: /bin/sh
  args:
  - '-c'
  - |
    git clone git@github.com:$_GITHUB_ORG/$_GITHUB_REPO-k8s.git && \
    cd $_GITHUB_REPO-k8s && \
    git checkout candidate-dev && \
    git config --global user.email $(gcloud auth list --filter=status:ACTIVE --format='value(account)')
  volumes:
  - name: 'ssh'
    path: /root/.ssh

# update helm values 
- name: 'gcr.io/cloud-builders/git'
  id: Update helm values
  entrypoint: /bin/sh
  args:
  - '-c'
  - |
     sed "s/GOOGLE_CLOUD_PROJECT/${PROJECT_ID}/g" $_GITHUB_REPO-k8s/values.yaml.tpl | \
     sed "s/COMMIT_SHA/${SHORT_SHA}/g" > $_GITHUB_REPO-k8s/$_EXEC_NAME/values.yaml
  volumes:
  - name: 'ssh'
    path: /root/.ssh

- name: 'gcr.io/$PROJECT_ID/helm'
  id: generate manifest
  entrypoint: bash
  args:
  - '-c'
  - |
    cd $_GITHUB_REPO-k8s && \
    helm template --output-dir ./manifests ./$_EXEC_NAME
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=us-central1-b'
  - 'CLOUDSDK_CONTAINER_CLUSTER=hello-cloudbuild'

# push new helm values to k8s repo
- name: 'gcr.io/cloud-builders/git'
  id: commit new helm values
  entrypoint: /bin/sh
  args:
  - '-c'
  - |
    cd $_GITHUB_REPO-k8s && \
    git add $_EXEC_NAME manifests && \
    git commit -m "Deploying image gcr.io./${PROJECT_ID}/$_EXEC_NAME:${SHORT_SHA} 
    Build from commit ${Commit_SHA} of repository $_GITHUB_REPO" && \
    git push origin candidate-dev
  volumes:
  - name: 'ssh'
    path: /root/.ssh